package snowflake

import (
	"strconv"
	"time"
)

// Snowflake is an ID generated by a Generator
type Snowflake string

// Int returns the integer version of a snowflake
func (s Snowflake) Int() int64 {
	i, _ := strconv.ParseInt(string(s), 10, 0)
	return i
}

// ToTime converts the snowflake to a timestamp
func (s Snowflake) ToTime(epoch time.Time) time.Time {
	i, _ := strconv.ParseInt(string(s), 10, 64)
	timestamp := (i >> 22) + int64(epoch.UnixNano()/1000000)

	return time.Unix(0, timestamp*1000000).UTC()
}

func (s Snowflake) String() string {
	return string(s)
}
