package snowflake

import (
	"fmt"
	"time"
)

// Snowflake is an ID generated by a Generator
type Snowflake uint64

// ID is an alias for Snowflake
type ID = Snowflake

// Int returns the integer version of a snowflake
func (s Snowflake) Int() int64 {
	return int64(s)
}

// ToTime converts the snowflake to a timestamp
func (s Snowflake) ToTime(epoch time.Time) time.Time {
	timestamp := int64((s >> 22)) + int64(epoch.UnixNano()/1000000)

	return time.Unix(0, timestamp*1000000).UTC()
}

func (s Snowflake) String() string {
	return fmt.Sprintf("%d", s)
}
